-- nvim-tree remaps
-- 
-- local nvim_tree_api = require('nvim-tree.api')
-- 
-- local function opts(desc)
--     local bufnr = vim.api.nvim_get_current_buf()
--     return { desc = "nvim-tree: " .. desc, buffer = bufnr, noremap = true, silent = true, nowait = true }
--     nvim_tree_api.node.open.tab(node)
--     vim.keymap.set("n", "<CR>",           nvim_tree_api.node.open.tab(nvim_tree_api.tree.get_node_under_cursor()),                 opts("Open")) -- automatically close the tree when opening a file
-- end
-- 
